image: php:5.6


stages:
  - test


before_script:
  - apt-get update -yqq
  - apt-get install -yqq wget


Tests:
  stage: test
  tags:
    - php
    - vps
  script:
    # Installation des outils pour les tests automatiques
    - wget https://phar.phpunit.de/phpunit-5.7.phar
    - chmod +x phpunit-5.7.phar
    - mv phpunit-5.7.phar /usr/local/bin/phpunit
    - pecl install xdebug
    - docker-php-ext-enable xdebug

    # Execution des tests unitaire (Colored Coverage)
    # Ajout d'un titre pout la suite de l'affichage
    # Traite le flux affiché à l'aide de tee en simultanné
    # Supprime la colorisation et l'affiche pour le code coverage GitLab
    # Fonctionne même si les tests échouent.
    - >
      (phpunit; echo; echo ;echo "STDOUT For GitLab RegExp :"; echo)
      | tee >(grep 'Lines' | sed -r "s/\x1B\[([0-9]{1,2}(;[0-9]{1,2})?)?[mGK]//g")
