#!/bin/bash
#
# @author    Nicolas DUPRE
# @release   23/10/2017
#
# Nettoyage des fichiers servant à la comparaison.
cd ../resources/cli
rm -r *
cd -

# Nettoyage du dossier actuel pour jouer les commandes.
ls -a | egrep -v "^\.+$|makeCLItxt|CommandTest" | xargs -r rm -r

# Aide
SYSLang -h > ../resources/cli/help.txt 2>&1

# Installation
SYSLang --install > ../resources/cli/install.txt 2>&1
SYSLang --install > ../resources/cli/installed.txt 2>&1

# Ajouter une langue
SYSLang --add-languages fr-FR:Français > ../resources/cli/add-lang-frFR.txt 2>&1
SYSLang --add-languages en-EN:English --default > ../resources/cli/add-lang-enEN.txt 2>&1
SYSLang --add-languages Japonais > ../resources/cli/add-lang-Japonais.txt 2>&1

# Définir la langue par défault
SYSLang --set-default-lang fr-FR > ../resources/cli/set-def-lang-frFR.txt 2>&1
SYSLang --set-default-lang jp-JP > ../resources/cli/set-def-lang-jpJP.txt 2>&1

# Supprimer une langue
SYSLang --remove-languages en-EN > ../resources/cli/rem-lang-enEN.txt 2>&1
SYSLang --remove-lang Japonais > ../resources/cli/rem-lang-Japonais.txt 2>&1

# Nettoyage du dossier actuel pour jouer les tests phpunit
ls -a | egrep -v "^\.+$|makeCLItxt|CommandTest" | xargs -r rm -r
